name: Maven Build
type: job
stages:
  - Build
steps:
  - name: Maven Build
    type: plugin
    plugin: oci/pipeline-plugin-devops-commons:2.0.3
    stage_output: build
    script:
      - mvn clean install
