scrape_configs:
  - job_name: 'feed-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['feed-service.default.svc.cluster.local:8086']

  - job_name: 'follow-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['follow-service.default.svc.cluster.local:443']

  - job_name: 'kafka-consumer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kafka-consumer-service.default.svc.cluster.local:80']

  - job_name: 'post-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['post-service.default.svc.cluster.local:443']
