apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest  # Use the official MongoDB image
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /bitnami/mongodb/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-data
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
