apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: us-sanjose-1.ocir.io/ax0zk0xsm3t8/post-service:$BUILDRUN_HASH
          ports:
            - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8090'
spec:
  selector:
    app: post-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: ClusterIP
