apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service
          image: moukthikavuyyuru/feed-service:test
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
---

apiVersion: v1
kind: Service
metadata:
  name: feed-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8086'
spec:
  selector:
    app: feed-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
  type: ClusterIP
