apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follow-service
  template:
    metadata:
      labels:
        app: follow-service
    spec:
      containers:
        - name: follow-service
          image: moukthikavuyyuru/follow-service:$BUILDRUN_HASH
          ports:
            - containerPort: 8050

---
apiVersion: v1
kind: Service
metadata:
  name: follow-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8050'
spec:
  selector:
    app: follow-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8050
  type: ClusterIP
