apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer-service
  template:
    metadata:
      labels:
        app: kafka-consumer-service
    spec:
      containers:
        - name: kafka-consumer-service
          image: moukthikavuyyuru/kafka-consumer-service:latest
          ports:
            - containerPort: 8084

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
spec:
  selector:
    app: kafka-consumer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: NodePort