apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer-service
  template:
    metadata:
      labels:
        app: kafka-consumer-service
    spec:
      containers:
        - name: kafka-consumer-service
          image: moukthikavuyyuru/kafka-consumer-service:$BUILDRUN_HASH
          ports:
            - containerPort: 8084

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8084'
spec:
  selector:
    app: kafka-consumer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP